'use strict';
const fs = require('node:fs');
function flatten(node, out = {}) { if (!node || typeof node !== 'object') return out; if (node.idShort && Object.prototype.hasOwnProperty.call(node, 'value') && typeof node.value !== 'object') out[node.idShort] = node.value; for (const value of Object.values(node)) { if (Array.isArray(value)) value.forEach((item) => flatten(item, out)); else if (value && typeof value === 'object') flatten(value, out); } return out; }
class Aas {
  constructor(file, config) { this.raw = JSON.parse(fs.readFileSync(file, 'utf8')); this.config = config; this.shell = this.raw.assetAdministrationShells?.[0] || {}; this.values = flatten(this.raw); }
  prop(name, fallback = '') { return this.values[name] ?? fallback; }
  description() { const ids = Object.fromEntries((this.shell.assetInformation?.specificAssetIds || []).map((x) => [x.name, x.value])); return { cpsId: ids.cpsId || this.config.cpsId, assetName: ids.assetName || this.config.cpsName, aasId: this.shell.id || '', aasIdShort: this.shell.idShort || '', description: this.shell.description?.[0]?.text || '', manufacturer: ids.manufacturer || this.prop('ManufacturerName'), assetType: ids.assetType || '', serialNumber: ids.serialNumber || this.prop('SerialNumber'), globalAssetId: this.shell.assetInformation?.globalAssetId || '', dashboardUrl: this.prop('DashboardURL'), datasheetUrl: this.prop('DatasheetPDF', '/api/cps7/datasheet/pdf'), scientificReportUrl: this.prop('ScientificReportPDF'), currentState: null }; }
  interfaces() { const values = this.values; return { primaryProtocol: values.PrimaryProtocol || 'MQTT', brokerHost: values.BrokerHost || '', brokerPort: Number(values.BrokerPort || 1883), brokerWebSocketPort: Number(values.BrokerWebSocketPort || 8000), brokerSecureWebSocketPort: Number(values.BrokerSecureWebSocketPort || 8884), qosDefault: Number(values.QoSDefault || 1), retainDefault: values.RetainDefault || 'false', payloadFormat: values.PayloadFormat || 'JSON', baseTopic: values.BaseTopic || this.config.baseTopic, topics: { command: 'cps7/cmd', status: 'cps7/status', ack: 'cps7/ack', health: 'cps7/health', data: 'cps7/data', oee: 'cps7/oee', learning: 'acsm/cps7/learning', sensorInput: 'cps7/sensordata' } }; }
  lifecycle() { return { supportedPhases: this.prop('SupportedPhases'), aasCurrentPhase: this.prop('CurrentPhase'), lifecyclePhase: 'plug', operationModes: ['running', 'stopped', 'maintenance'], return: 'reintegration process' }; }
}
module.exports = Aas;
