'use strict';
const fs = require('node:fs');
const http = require('node:http');
const config = require('./config');
const State = require('./state');
const Lifecycle = require('./lifecycle');
const Telemetry = require('./telemetry');
const Oee = require('./oee');
const Analytics = require('./analytics');
const Aas = require('./aas');
const Mqtt = require('./mqtt');
const { calculate: calculateHealth } = require('./health');

const state = new State(config);
const lifecycle = new Lifecycle(state);
const telemetry = new Telemetry(state);
const oee = new Oee(state);
const analytics = new Analytics(state);
const aas = new Aas(config.aasPath, config);
const mqtt = new Mqtt(config, (command) => {
  const action = String(command?.action || '').toUpperCase();
  if (config.runtimeMode === 'active' && command?.type === 'governed_action') applyGovernedAction(command, false);
  else if (config.runtimeMode === 'active' && action === 'ADJUST_TRANSPORT_SPEED') applyGovernedAction(command, false);
  else if (config.runtimeMode === 'active') applyCommand(command.action, false);
});

function featureStatus() { return state.getState().capabilityState.status || 'maintenance'; }
function status() { const s = state.getState(); const h = s.health || calculateHealth(featureStatus()); return { cpsId: config.cpsId, cpsName: config.cpsName, state: s.operationMode, lifecyclePhase: s.lifecyclePhase, operationMode: s.operationMode, playEnabled: s.playEnabled, feature: 'to_ship_the_part', featureStatus: featureStatus(), healthScore: h.healthScore, healthLabel: h.healthLabel, featureCount: 1, summary: { [featureStatus()]: 1 }, ts: Date.now() }; }
function description() { return { ...aas.description(), currentState: state.getState().operationMode, ts: Date.now() }; }
function health() { const s = state.getState(); const h = s.health || calculateHealth(featureStatus()); return { cpsId: config.cpsId, cpsName: config.cpsName, ...h, operationalState: s.operationMode, lifecyclePhase: s.lifecyclePhase, lastHeartbeat: s.timestamps.updatedAt || s.timestamps.startedAt, ts: Date.now() }; }
function summary() { const s = state.getState(); const t = s.lastTelemetry || s.lastValidTelemetry || {}; const h = s.health || calculateHealth(featureStatus()); const o = s.oee || {}; return { cpsId: config.cpsId, assetName: config.cpsName, state: s.operationMode, lifecyclePhase: s.lifecyclePhase, operationMode: s.operationMode, playEnabled: s.playEnabled, healthScore: h.healthScore, healthLabel: h.healthLabel, oee: o.oee || 0, availability: o.availability || 0, performance: o.performance || 0, quality: o.quality || 0, currentTemperature: Number(t.CurrentTemperature || 0), currentRPM: Number(t.CurrentRPM || 0), currentTorque: Number(t.CurrentTorque || 0), pieceCounter: Number(t.PieceCounter || 0), cycleTimeMs: Number(t.CycleTimeMs || 0), operationModeReported: t.OperationMode || 'unknown', featureName: 'to_ship_the_part', featureStatus: featureStatus(), currentPhase: s.lifecyclePhase, supportedPhases: aas.prop('SupportedPhases'), ts: Date.now() }; }
function data() { const s = state.getState(); return { cpsId: config.cpsId, assetName: config.cpsName, operationalData: s.lastTelemetry || s.lastValidTelemetry || null, sensorActuatorData: s.sensorInput, lastValidTelemetry: s.lastValidTelemetry, ts: new Date().toISOString() }; }
function sendJson(res, code, value) { res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8' }); res.end(JSON.stringify(value)); }
function applyCommand(action, fromRest) { let next; try { next = lifecycle.command(action); } catch (_) { return { ok: false, error: 'Unsupported action' }; } if (fromRest && config.runtimeMode === 'shadow') return { ok: true, shadowMode: true, action, published: false, state: next }; if (config.runtimeMode === 'active') { mqtt.publish(`${config.baseTopic}/ack`, { cpsId: config.cpsId, cpsName: config.cpsName, action, ok: true, playEnabled: next.playEnabled, status: next.operationMode, ts: new Date().toISOString() }); mqtt.publish(`${config.baseTopic}/status`, status()); } return { ok: true, shadowMode: config.runtimeMode !== 'active', action, state: next }; }
function applyGovernedAction(command = {}, fromRest = false) { const action = String(command.action || '').toUpperCase(); if (action !== 'ADJUST_TRANSPORT_SPEED') return { ok: false, accepted: false, applied: false, error: 'Unsupported governed action' }; const variation = Math.abs(Number(command.variation ?? command.requestedValue)); const requestedValue = Number(command.requestedValue ?? command.variation); if (!Number.isFinite(variation) || !Number.isFinite(requestedValue)) return { ok: false, accepted: false, applied: false, error: 'Invalid variation' }; const current = state.getState(); const application = telemetry.applyTransportSpeedAdjustment(requestedValue); if (!application.applied) return { ok: false, ...application }; const executedAt = new Date().toISOString(); const record = { ...command, action, variation, requestedValue, unit: command.unit || '%', executedAt, transport: fromRest ? 'REST' : 'MQTT', result: 'transport_speed_adjustment_applied', ...application }; const next = state.updateState({ capabilityState: { ...(current.capabilityState || {}), parameters: { ...(current.capabilityState?.parameters || {}), transportSpeedPct: application.newValue, transportSpeedAdjustmentPct: requestedValue }, lastGovernedAction: record }, governedActions: [record, ...(current.governedActions || [])].slice(0, 50) }); if (config.runtimeMode === 'active') { mqtt.publish(`${config.baseTopic}/ack`, { cpsId: config.cpsId, cpsName: config.cpsName, type: 'governed_action', action, ok: true, accepted: true, applied: true, variation, requestedValue, previousValue: application.previousValue, newValue: application.newValue, unit: record.unit, ts: executedAt }); mqtt.publish(`${config.baseTopic}/status`, status()); } return { ok: true, accepted: true, applied: true, cpsId: config.cpsId, action, executionStatus: 'EXECUTED', executedAt, previousValue: application.previousValue, newValue: application.newValue, appliedVariation: application.appliedVariation, limits: application.limits, state: next, record }; }
function handle(req, res) { const url = new URL(req.url, 'http://localhost'); if (req.method === 'GET' && url.pathname === '/api/cps/description') return sendJson(res, 200, description()); if (req.method === 'GET' && url.pathname === '/api/cps/status') return sendJson(res, 200, status()); if (req.method === 'GET' && url.pathname === '/api/cps/health') return sendJson(res, 200, health()); if (req.method === 'GET' && url.pathname === '/api/cps/summary') return sendJson(res, 200, summary()); if (req.method === 'GET' && url.pathname === '/api/cps/oee') return sendJson(res, 200, sOrEmpty(state.getOEE())); if (req.method === 'GET' && url.pathname === '/api/cps/data') return sendJson(res, 200, data()); if (req.method === 'GET' && url.pathname === '/api/cps/interfaces') return sendJson(res, 200, { ...aas.interfaces(), runtimeMode: config.runtimeMode, ts: Date.now() }); if (req.method === 'GET' && url.pathname === '/api/cps/lifecycle') return sendJson(res, 200, { cpsId: config.cpsId, assetName: config.cpsName, ...aas.lifecycle(), ...((s) => ({ lifecyclePhase: s.lifecyclePhase, operationMode: s.operationMode, playEnabled: s.playEnabled }))(state.getState()), ts: new Date().toISOString() }); if (req.method === 'GET' && url.pathname === '/api/cps/datasheet/pdf') { try { const pdf = fs.readFileSync(config.datasheetPath); res.writeHead(200, { 'Content-Type': 'application/pdf', 'Content-Disposition': 'inline; filename="cps7-datasheet.pdf"' }); return res.end(pdf); } catch (_) { return sendJson(res, 404, { error: 'Datasheet not available' }); } } if (req.method === 'POST' && url.pathname === '/api/cps/command') { let body = ''; req.on('data', (chunk) => { body += chunk; }); req.on('end', () => { let command; try { command = JSON.parse(body || '{}'); } catch (_) { return sendJson(res, 400, { error: 'Invalid JSON' }); } if (!['play', 'stop', 'maintenance', 'unplug', 'return'].includes(String(command.action).toLowerCase())) return sendJson(res, 400, { error: 'Unsupported action' }); return sendJson(res, 200, applyCommand(String(command.action).toLowerCase(), true)); }); return; } if (req.method === 'POST' && url.pathname === '/api/cps/governed-action') { let body = ''; req.on('data', (chunk) => { body += chunk; }); req.on('end', () => { let command; try { command = JSON.parse(body || '{}'); } catch (_) { return sendJson(res, 400, { error: 'Invalid JSON' }); } return sendJson(res, 200, applyGovernedAction(command, true)); }); return; } return sendJson(res, 404, { error: 'Not found' }); }
function sOrEmpty(value) { return value || { cpsId: config.cpsId, assetName: config.cpsName, availability: 0, performance: 0, quality: 0, oee: 0, ts: Date.now() }; }
const server = http.createServer(handle);
server.listen(config.httpPort, () => { console.log(`CPS-7 service listening on http://localhost:${config.httpPort} (${config.runtimeMode})`); mqtt.start(); });
const timer = setInterval(() => { const sample = telemetry.sample(); if (!sample) return; const feature = sample.OperationMode === 'stop' ? 'stopped' : 'active'; const currentState = state.getState(); state.updateState({ capabilityState: { ...(currentState.capabilityState || {}), feature: 'to_ship_the_part', status: feature }, lastTelemetry: sample, lastValidTelemetry: sample }); const h = calculateHealth(feature, sample); state.setHealth(h); const value = oee.calculate(feature, sample); const intelligence = analytics.update(sample, value, h, feature); if (config.runtimeMode === 'active') { mqtt.publish(`${config.baseTopic}/data`, sample); mqtt.publish(`${config.baseTopic}/sensordata`, state.getState().sensorInput || {}); mqtt.publish(`${config.baseTopic}/health`, { cpsId: config.cpsId, cpsName: config.cpsName, ...h, ts: Date.now() }); mqtt.publish(`${config.baseTopic}/oee`, value); mqtt.publish(`${config.baseTopic}/status`, status()); mqtt.publish('acsm/cps7/learning', { ...intelligence, cpsId: config.cpsId, cpsName: config.cpsName, ts: Date.now() }); } }, config.telemetryIntervalMs);
function close() { clearInterval(timer); mqtt.close(); server.close(() => process.exit(0)); }
process.on('SIGTERM', close); process.on('SIGINT', close);
